### ISSUE TITLE
请问如何打包执行

### ISSUE THREAD

**Issue by eddyzh** [cmlbeliever/SpringBatch#1]
想在命令行下执行。
如何打出jar包？
我用Eclipse的导出功能导出jar包，将第三方的jar包导出到单独的文件夹，没执行成功。
用Maven的install得到的jar包执行，mybatis扫描之后就不动了，进程也没办法杀掉，生成的三个日志内容也是空的。

可以把打包执行的方法加到ReadMe中吗？

**Comment by cmlbeliever** [comment]
打包功能已添加，readme已更新。
