### ISSUE TITLE
能说明一下事务是怎么使用的吗？

### ISSUE THREAD

**Issue by eddyzh** [cmlbeliever/SpringBatch#2]
我看项目里有关于事务的代码，但是没弄明白怎么使用。

**Comment by cmlbeliever** [comment]
SpringBatch默认一个tasklet是一个事务，一个commit是一个事务，具体的可以看官方文档。
如果需要自己控制事务，则使用注解@Transactional进行事务标记。这个属于Spring的东西，你可以看下官方文档说明。
